# Generated by Django 6.0 on 2026-01-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
